apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator-daniel


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator-daniel
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator-daniel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-daniel
subjects:
- kind: ServiceAccount
  name: prometheus-operator-daniel
  namespace: daniel

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-operator-daniel
spec:
  serviceAccountName: prometheus-operator-daniel
  podMonitorSelector:
    matchLabels:
      team: obs-daniel
  resources:
    requests:
      memory: 100Mi
  enableAdminAPI: false

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-daniel
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30777
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus-operator-daniel
